config/routes.rb
Dumbly::Application.routes.draw do

  resources :inputs
  resources :page_view

  root :to => "inputs#new"
  get "inputs/new"

  match "page_view/:input_id" => "page_view#create"
  match "page_views" => "page_view#show"

  Input.all.each do |input|
    get "/#{input.shortened}" => redirect("#{input.original}")
  end

end

app/models/input.rb
class Input < ActiveRecord::Base
  attr_accessible :original, :shortened, :id

  has_many :page_view

  validates :original, :format => { :with => /^http/ }

  def self.shorten
    array = []
    3.times { array << [rand(97..123).chr, rand(10)] }
    array.flatten.shuffle.join
  end

  # def add_page_view
  #    @page_view = PageView.new(:input_id => params[:input_id])
  #    @page_view.save
  #  end

end

app/models/page_view.rb
class PageView < ActiveRecord::Base
  attr_accessible :input_id
  belongs_to :input
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController


  def index
    # @input = Input.new
  end

  def new
    @input = Input.new
  end

  def create
    @input = Input.new(params[:input].merge(:shortened => Input.shorten))
    @input.save ? (redirect_to @input) : (render :new)
  end

  def show
    @input = Input.find(params[:id])
  end
end

app/controllers/page_view_controller.rb
class PageViewController < ApplicationController
  # def new
  #   @page_view = PageView.new(:input_id => params[:input_id])
  # end

  def create
    @url = Input.find(params[:input_id]).original
    @page_view = PageView.create(:input_id => params[:input_id])
    redirect_to @url if @page_view.save
  end

  def show
    @page_views = PageView.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/helpers/page_view_helper.rb
module PageViewHelper

  def list_page_views
    div_for(PageView.all) do |view|
      view.id
    end
  end

end

app/views/inputs/show.html.erb
<h1>Thanks for choding.</h1>
<p>
  original url: <%= @input.original %><br/><br/>
  choded url:<%= link_to "localhost:3000/#{@input.shortened}", page_view_path, :input_id => @input.id, :yo => "#{@input.original}", :method => :post %>
</p>

<%= image_tag("chortbus.jpeg")%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dumbly</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>



</body>
</html>

app/views/layouts/new.html.erb
<h1>Chode.ly</h1>

<h4> short. wide. fast. </h4>

<% if @input.errors.any? %>
  <ul>
    <% @input.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @input do |f| %>
  <p>
    <%= f.label :url %><br>
    <%= f.text_field :original %>

    <% f.label :shorten %>
    <%= f.submit value="Choden" %>
  </p>
<% end %>

<%= link_to "chodes of the past", 'inputs' %>

app/views/page_view/show.html.erb
<h1>
<% @array = []%>
<% PageView.find(:all).each do |view|%>
<%Input.find_by_id(view.input_id) do |input|%>
<% @array << input.original if !input.nil? %><br/>
<% end %>
<% end %>
<% @hash =  @array.inject(Hash.new(0)) { |total, e| total[e] += 1; total} %>
<%= "url: #{@hash.first.first}.........page_views: #{@hash.first.second}"%>
</h1>